### ISSUE TITLE
Use options where possible

### ISSUE THREAD

**Issue by samreid** [phetsims/fractions-intro#10]
I noticed this code in a recent commit:

```js
    var maxText = new Text( maxString, { font: font, fill: options.fill } );
    maxText.bottom = maxNumberSpinner.top;
    maxText.left = maxNumberOfUnitsText.left;
```

Where possible, it is often preferable to include all settings into the options argument, like so:

```js
    var maxText = new Text( maxString, { 
      font: font, 
      fill: options.fill,
      bottom:  maxNumberSpinner.top,
      left: maxNumberOfUnitsText.left
    } );
```

Can you make this change and see if there are other parts of the code that should follow this same pattern?

**Comment by davisv7** [comment]
I've moved the arguments into the options for maxText. When I looked through other functions, I didn't find this same issue.

**Comment by samreid** [comment]
Thanks @davisv007, looks great!  As a new policy for you and your team, I'd like to recommend the following:

When an issue is reported by a code reviewer, designer or quality assurance team member, after you and your team has addressed the issue, please comment about what was done and reassign back to the original reporter to review/test and close.

Please check yourself off when you have reviewed this new policy.  If you are the last one, please close the issue.

- [x] @davisv007 
- [x] @michaelm396 
- [x] @coledu

**Comment by michaelm396** [comment]
All of the team members have reviewed this recommendation. I'm closing this issue. Thank you
