### ISSUE TITLE
JSDoc incorrect for MaxSpinner

### ISSUE THREAD

**Issue by samreid** [phetsims/fractions-intro#11]
MaxSpinner.js shows this JSDoc:

```js
/**
 * Node for the fraction with up/down spinners for denominator/numerator
 *
 * @author Vincent Davis (Berea College)
 */
```

It seems like it may have been copy pasted from elsewhere.  This issue is a reminder to update it.

**Comment by davisv7** [comment]
Fixed the JSDoc for MaxSpinner.

**Comment by samreid** [comment]
Looks great, thanks!
