### ISSUE TITLE
Rename maxNumberOfUnitsProperty to maxProperty

### ISSUE THREAD

**Issue by samreid** [phetsims/fractions-intro#13]
In my opinion, it seems like "numberOfUnits" in the term maxNumberOfUnitsProperty is redundant, and a better name for the variable would be `maxProperty` since it indicates the maximum value the fraction can take.  Another reason I prefer the name `maxProperty` is because within the sim, the value is referred to as "max" not "max number of units".

![image](https://cloud.githubusercontent.com/assets/679486/26088383/1f4e417a-39b4-11e7-894f-919bf2a865f9.png)

Assigned to @veillette for discussion, prioritization and delegation.

**Comment by veillette** [comment]
@michaelm396 , please refactor maxNumberOfUnitsProperty to maxProperty throughout the simulation. Make sure to refactor all comments as well.

**Comment by michaelm396** [comment]
I refactored the [maxNumberOfUnitsPropety, MAX_NUMBER_OF_UNITS_RANGE, maxNumberOfUnits, maxNumberText, and maxText] into [maxProperty, MAX_RANGE, max, maxValueText, and maxLabelText] throughout the simulation.

**Comment by samreid** [comment]
Looks great, thanks!  Also, @michaelm396 are you committing from @veillette's account?

**Comment by michaelm396** [comment]
We are currently trying to figure out the committing errors. IntelliJ is committing with the incorrect user logon, but I did in fact refactor the changes. Thanks.

**Comment by samreid** [comment]
Since the refactoring looks good, I'll close this issue.  Feel free to open a new issue about correcting the IntelliJ credentials, if you wish.
