### ISSUE TITLE
Generalize NumberLineNode

### ISSUE THREAD

**Issue by veillette** [phetsims/fractions-intro#14]
NumberLineNode should be reusable for the equality lab simulation.

![image](https://cloud.githubusercontent.com/assets/7633344/26109206/c4dab232-3a1c-11e7-98d3-4e5d14c37eb6.png)

It is very similar to the number Line on the intro tab.
![image](https://cloud.githubusercontent.com/assets/7633344/26109230/dbeb42f2-3a1c-11e7-97f8-cd3291338108.png)

There are five main distinctions:

 - it is vertical
 - it has left and right tickmarks that can be set independently
 - it has a pink arrow marker
 - the circle marker does not have a drag handler.
 - the number line is of fixed length

**Comment by veillette** [comment]
![image](https://cloud.githubusercontent.com/assets/7633344/26110256/cbe72a94-3a1f-11e7-8cbd-4794cdfb55e4.png)

I have set it up such that the number line can be vertically aligned when passing the appropriate options. 
Assigning to @michaelm396 to add the pink arrow in vertical mode.

**Comment by michaelm396** [comment]
@coledu and I have successfully generalized the NumberLineNode file. It now displays a pink arrow and pink dot that slides along the Number Line when displayNode: true. Now reassigning this issue to @veillette for a check. Thank you

**Comment by coledu** [comment]
I have added multiplication faction property to number line node and modify the append tick function to take in an option for direction that determine which side the tick appear on or if it is symmetric. This add the functionality of setting the left and right tick marks independently of one other. This will be useful in the equality lab tab. Sorry, I forgot to reference the issue in my commit. Here is the id:
93bedbe2448b8a55de21dbab0ff98dda84a8f6da
Here is a picture of the results:
![image](https://cloud.githubusercontent.com/assets/26030529/26208796/046aa842-3bb9-11e7-81bb-cdf93f4c7f81.png)

**Comment by coledu** [comment]
Assigning back to @veillette for review.

**Comment by veillette** [comment]
This was well done. It can be used for the third tab. Thanks @coledu . Closing
