### ISSUE TITLE
cylinder color

### ISSUE THREAD

**Issue by coledu** [phetsims/fractions-intro#15]
In the process of porting fraction intro from java to JavaScript we realize that the cylinder have liquid that fill the container. And we think it might be more appropriate to use blue instead of yellow to represent water. I have created a mockup so you can see the difference. I am open to any suggestions or pixel polish or changing of the gradient of the cylinder. 
Old:
![image](https://cloud.githubusercontent.com/assets/26030529/26170724/6edb04b4-3b10-11e7-9095-21244a3e0f2b.png)
New:
![image](https://cloud.githubusercontent.com/assets/26030529/26170706/646d4136-3b10-11e7-80fc-b8bee6c917dc.png)

**Comment by ariel-phet** [comment]
@coledu the original thought behind the design was to have lots of different colorful and "fun" choices for shapes and such. We would probably want to retain yellow as a color (so for instance make the rectangle yellow) if we make the liquid be blue.

**Comment by ariel-phet** [comment]
Assigning to @amanda-phet to make the call.

**Comment by amanda-phet** [comment]
I always thought it was juice! Blue water seems to work here as well, but I agree we'd want to make the rectangle yellow to balance it out. A "warm" tone like FFE600 would work well.

**Comment by coledu** [comment]
I have changed of the color of the rectangle icon to yellow.

**Comment by coledu** [comment]
I change the color of the beaker in representation panel to the color that @amanda-phet wanted. I also added cylinder node to the panel as well. I am waiting until we made the rectangle before assigning somebody to review and close this issue. Leaving myself assign for now.

**Comment by coledu** [comment]
I have change all the color. Closing this issue as @veillette say.
