### ISSUE TITLE
Recommend file for representation enumeration

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/fractions-intro#16]
Currently, the enumeration is an array of strings:

```js
  var VALID_REPRESENTATION_VALUES = [
    'circle',
    'horizontal-bar',
    'vertical-bar',
    'beaker',
    'cake',
    'number-line'
  ];
```

I'd recommend something like area-builder's GameState, e.g.:
```js
  // modules
  var areaBuilder = require( 'AREA_BUILDER/areaBuilder' );

  var GameState = {
    CHOOSING_LEVEL: 'choosingLevel',
    PRESENTING_INTERACTIVE_CHALLENGE: 'presentingInteractiveChallenge',
    SHOWING_CORRECT_ANSWER_FEEDBACK: 'showingCorrectAnswerFeedback',
    SHOWING_INCORRECT_ANSWER_FEEDBACK_TRY_AGAIN: 'showingIncorrectAnswerFeedbackTryAgain',
    SHOWING_INCORRECT_ANSWER_FEEDBACK_MOVE_ON: 'showingIncorrectAnswerFeedbackMoveOn',
    DISPLAYING_CORRECT_ANSWER: 'displayingCorrectAnswer',
    SHOWING_LEVEL_RESULTS: 'showingLevelResults'
  };

  // verify that enum is immutable, without the runtime penalty in production code
  if ( assert ) { Object.freeze( GameState ); }

  areaBuilder.register( 'GameState', GameState );

  return GameState;
```
but with an additional array (`GameState.VALUES`?) so that it can be used for Property's validValues.

**Comment by veillette** [comment]
@michaelm396  will take the lead on this issue.

**Comment by michaelm396** [comment]
I have committed the RepresentationPanel.js file and pushed the changes. I am now assigning this issue to @jonathanolson in order to evaluate the updates. Thank you.

**Comment by jonathanolson** [comment]
I'd recommend potentially naming the enumeration `Representation`, since I'm not sure what the 'State' part would be describing? (GameState is describing one of the states the game can be in, here you're describing which representation is being shown).

**Comment by jonathanolson** [comment]
> veillette assigned jonathanolson and unassigned michaelm396 18 minutes ago

Let me know if I can clarify (as I was reassigned above?), waiting on a response about renaming RepresentationState => Representation (or something else) as noted above.

**Comment by veillette** [comment]
my oversight.. We will take a look at renaming to Representation.

**Comment by jonathanolson** [comment]
Additionally, you'll want to change documentation from things like
```
@param {Property.<string>} representationProperty
```
to use `{Property.<Representation>}` (it gets treated as its own type for documentation).

**Comment by michaelm396** [comment]
I have made the recommended changes to the parameters of "IntroModel.js" and "RepresentationPanel.js". I am now assigning this issue to @jonathanolson for further review. 

Thank you.

**Comment by jonathanolson** [comment]
Looks great, thanks!
