### ISSUE TITLE
Redundant Property values check

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/fractions-intro#17]
In IntroModel, the following check is not needed:
```js
    // check for validity of representation, present for the lifetime of the sim
    this.representationProperty.link( function( representation ) {
      assert && assert( _.includes( VALID_REPRESENTATION_VALUES, representation ), 'invalid representation: ' + representation );
    } );
```
because the equivalent happens by specifying the validValues on the Property directly.

**Comment by michaelm396** [comment]
I have made the necessary changes to the "IntroModel.j" file. I removed the check statement, specifically for the "representationProperty" (Link to file) : d4a7c0efe7889d3a7a6b0b4c6e27f841b07c51c2 

Assigning issue to @jonathanolson for further review.

Thank you.

**Comment by jonathanolson** [comment]
Looks good, thanks!
