### ISSUE TITLE
Color fill preferred over gradient with no variation

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/fractions-intro#18]
In BeakerNode, the following gradient could be replaced with a constant color value:
```js
var fullCapFillGradient = new LinearGradient( -options.beakerWidth / 2, 0, options.beakerWidth / 2, 0 )
  .addColorStop( 0, '#72D2F2' )
  .addColorStop( 1, '#72D2F2' );
```

**Comment by jonathanolson** [comment]
Presumably also the mainGradient / capGradient parameters to createBeaker would change to mainFill and capFill?

**Comment by coledu** [comment]
@davisv007 and I refactored mainGradient and capGradient to mainFill and capFill. We also replaced the fullCapFill with a color. With our last commit: 856ec05cb330c38e5a68ea22ed796f841ad0b2f5
Reassigning to @jonathanolson for review.

**Comment by jonathanolson** [comment]
Looks good, but you'll want to update the `{LinearGradient}` type documentation to something like `{LinearGradient|string}`. Additionally, keep https://github.com/phetsims/fractions-intro/issues/21 in mind, as it may preempt some of this.

**Comment by davisv7** [comment]
The type documentation has been updated. Back to @jonathanolson for review.

**Comment by jonathanolson** [comment]
Looks great, thanks!
