### ISSUE TITLE
Refactoring to avoid repeated color values

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/fractions-intro#19]
In BeakerNode, the following code has repeated color values that could be missed in future maintenance:
```js
// set the gradient on the surface of the empty Beaker to make it look more 3D
var emptyFillGradient = new LinearGradient( -options.beakerWidth / 2, 0, options.beakerWidth / 2, 0 )
  .addColorStop( 0, '#a9a9a9' )
  .addColorStop( 0.666, '#FFF' )
  .addColorStop( 0.782, '#FCFCFC' )
  .addColorStop( 1, '#a9a9a9' );

// set the gradient on the cap to be the reverse of the beaker
var emptyCapFillGradient = new LinearGradient( options.beakerWidth / 2, 0, -options.beakerWidth / 2, 0 )
  .addColorStop( 0, '#a9a9a9' )
  .addColorStop( 0.666, '#FFF' )
  .addColorStop( 0.782, '#FCFCFC' )
  .addColorStop( 1, '#a9a9a9' );
```

Usually I'd recommend extracting these color values into variables or some other method to get rid of the duplication.

In this case, it would be possible to avoid having two gradients, and instead do something like `capPath.setScaleMagnitude( -1, 1 )` so that it is flipped horizontally (flipping it horizontally, including the gradient), if that would work for future changes in the code.

**Comment by davisv7** [comment]
@jonathanolson I used the code you recommended to reverse the gradient. By adding onto an existing conditional I was able to preserve the cap gradient of the liquidBeaker.  Now there are only 3 different 'gradients' in use. 

I will extract the 4 colors to variables tomorrow.

**Comment by davisv7** [comment]
I extracted the colors to constants. Reassigning back to @jonathanolson for review.

**Comment by jonathanolson** [comment]
Looks good, thanks!
