### ISSUE TITLE
Future ratio constraints and the beaker

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/fractions-intro#21]
Currently, the code for displaying the beaker has a hard assumption that the liquid will either only be (a) completely full, or (b) low enough where liquid isn't visible from the top of the beaker (only through the glass).

Is that an acceptable constraint? I'd usually have the beaker split into two parts (the "front" and a small section of the "back" at the top) so that this wouldn't be an issue (and the see-through color wouldn't have to be handled separately from the directly-visible color).

Thoughts?

**Comment by jonathanolson** [comment]
Also, since opaque colors are used (instead of transparent colors), the line showing the back bottom of the beaker is true gray (would expect the front blue/reflection to affect its appearance). Currently throws off the perspective effect a bit.

**Comment by jonathanolson** [comment]
(Was assigned to @ariel-phet as he was lead on the Java version, couldn't find the design doc for the HTML5 version if there was one)

Original Java version shades things like I would expect with my described implementation:
![screen shot 2017-05-18 at 11 33 13 am](https://cloud.githubusercontent.com/assets/480878/26215528/e2d03f30-3bbd-11e7-893e-639476f0e02b.png)

**Comment by ariel-phet** [comment]
@jonathanolson agreed. There is not really an HTML5 design doc at the moment (since the java version is basically the spec).

**Comment by ariel-phet** [comment]
Assigning to @veillette and his team

**Comment by jonathanolson** [comment]
Ok, I'll describe in more depth my proposed solution:

The beaker would be separated into three layers:

- Bottom layer: the bottom-back of the beaker (the line) and the top "reversed gradient" cap
- Middle layer: the liquid's side and top
- Top layer: the front of the beaker, including the tick marks.

The beaker and liquid would use fills (mostly gradients) that would be mainly transparency-based. This means the front of the beaker would go between values with potentially varying alphas for colors (depending on the exact best way to make it look). This might mean that both the "shadow" and "highlight" parts have non-zero alpha, or there's the potential to have the "highlight" have zero alpha. This would blend with the liquid behind, and then with the bottom layer.

This should allow an arbitrary amount of liquid (and not switching the liquid "cap", as the liquid "cap" would always be the same color), so that the 15/16th case (if we ever animate through it) would look correct.

Let me know if you have any questions.

**Comment by coledu** [comment]
In my last commit, I modified BeakerNode.js. I made the beaker and liquid use transparent colors. I changed the order in which the cylinders are created to bottom-middle-top, and I changed the order it is added to the IntroScreenView. I would like to clarify your proposed solution. First, the changes I made do not seem to affect the image produced. Am I heading in the right direction with these changes? 
Second, how should the layers be separated in the cylinder? 

![image](https://cloud.githubusercontent.com/assets/26030529/26323334/71fdd51e-3efc-11e7-8138-4db5b44c76a0.png)

Is this what the layer should look like?
Third, what should the opacity be and should it be able to change dynamically? 
Fourth, could you clarify more on this sentence, "This should allow an arbitrary amount of liquid (and not switching the liquid "cap", as the liquid "cap" would always be the same color), so that the 15/16th case (if we ever animate through it) would look correct." Do you mean that if the cap of the beaker and the cap of the liquid intersect without the beaker being full that by using transparent colors we will keep the 3-D effect? 
Assigning to @jonathanolson to answer our questions and review our code.

**Comment by jonathanolson** [comment]
> Third, what should the opacity be and should it be able to change dynamically?

The opacity as would just be applied to the individual colors, not entire parts of cylinders.

> Do you mean that if the cap of the beaker and the cap of the liquid intersect without the beaker being full that by using transparent colors we will keep the 3-D effect?

I mean that when the beaker cap and liquid cap partially intersect, things should look "correct".

As an example, I've mocked up a quick-and-dirty example of what I mean (uses kite/scenery prefixes so it can run in Scenery's playground for easier testing).

Example images:
![beaker-5](https://cloud.githubusercontent.com/assets/480878/26330892/6d1b5940-3f0b-11e7-8458-3e8ea2bed976.PNG)
![beaker-1](https://cloud.githubusercontent.com/assets/480878/26330876/5aba567a-3f0b-11e7-8c8a-6408057b16cb.PNG)
![beaker-2](https://cloud.githubusercontent.com/assets/480878/26330880/613edbd8-3f0b-11e7-90b7-3078411ee580.PNG)
![beaker-3](https://cloud.githubusercontent.com/assets/480878/26330886/65316aa8-3f0b-11e7-9b4e-ea13f0fdb17f.PNG)
![beaker-4](https://cloud.githubusercontent.com/assets/480878/26330889/68967ec2-3f0b-11e7-83ea-d3b8c89572a6.PNG)

Note the opacity applied in the colors (and how the highlight is less transparent). It seems to look a bit nicer if the "back" isn't a cap only, but goes the length of the beaker (had to add a beaker bottom to have things look consistent).

Example code:
```js

var xRadius = 20;
var yRadius = 8;
var fullHeight = 100;
var height = 25;
var numTicks = 8;
var bucketFrontShape = new kite.Shape().ellipticalArc( 0, 0, xRadius, yRadius, 0, 0, Math.PI, false )
                                       .ellipticalArc( 0, -fullHeight, xRadius, yRadius, 0, Math.PI, 0, true ).close();
var bucketBackShape = new kite.Shape().ellipticalArc( 0, -fullHeight, xRadius, yRadius, 0, Math.PI, 0, false )
                                      .ellipticalArc( 0, 0, xRadius, yRadius, 0, 0, Math.PI, true ).close();
var bucketBottomShape = new kite.Shape().ellipticalArc( 0, 0, xRadius, yRadius, 0, 0, 2 * Math.PI, false );
var waterTopShape = new kite.Shape().ellipticalArc( 0, -height, xRadius, yRadius, 0, 0, Math.PI * 2, false ).close();
var waterSideShape = new kite.Shape().ellipticalArc( 0, -height, xRadius, yRadius, 0, Math.PI, 0, true )
                                     .ellipticalArc( 0, 0, xRadius, yRadius, 0, 0, Math.PI, false ).close();
var ticksShape = new kite.Shape();
for ( var i = 1; i < numTicks; i++ ) {
  var y = -fullHeight * ( numTicks - i ) / numTicks;
  ticksShape.moveTo( -xRadius, y ).ellipticalArc( 0, y, xRadius, yRadius, 0, Math.PI, Math.PI * ( i % 2 === 0 ? 0.7 : 0.8 ), true );
}

var EMPTY_BEAKER_COLOR = 'rgba(150,150,150,0.2)';
var WATER_SIDE_COLOR = 'rgba(30,193,248,0.8)';
var WATER_TOP_COLOR = 'rgba(70,200,238,0.8)';
var BEAKER_SHINE_COLOR = 'rgba(255,255,255,0.8)';

var glassGradient = new scenery.LinearGradient( -xRadius, 0, xRadius, 0 ).addColorStop( 0, EMPTY_BEAKER_COLOR )
                                                                         .addColorStop( 0.666, BEAKER_SHINE_COLOR )
                                                                         .addColorStop( 0.782, BEAKER_SHINE_COLOR )
                                                                         .addColorStop( 1, EMPTY_BEAKER_COLOR );

var bucketFront = new scenery.Path( bucketFrontShape, {
  stroke: 'grey',
  fill: glassGradient
} );
var bucketBack = new scenery.Path( bucketBackShape, {
  stroke: 'grey',
  fill: glassGradient
} );
bucketBack.setScaleMagnitude( -1, 1 );
var bucketBottom = new scenery.Path( bucketBottomShape, {
  stroke: 'grey',
  fill: EMPTY_BEAKER_COLOR
} );
var waterSide = new scenery.Path( waterSideShape, {
  stroke: 'black',
  fill: WATER_SIDE_COLOR
} );
var waterTop = new scenery.Path( waterTopShape, {
  fill: WATER_TOP_COLOR
} );
var ticks = new scenery.Path( ticksShape, {
  stroke: 'black'
} );

var beaker = new scenery.Node( {
  children: [
    bucketBack,
    bucketBottom,
    waterSide,
    waterTop,
    bucketFront,
    ticks
  ],
  top: 20,
  left: 20
} );

scene.addChild( beaker );
display.height = 640;
display.updateDisplay();
```

**Comment by coledu** [comment]
In my last commit , I took your suggestion and change the opacity of the color, reorder the way i draw the cylinder so it won't look like it have a cap only on it and look correctly. I also added a bottom to the beaker. I use the colors that your use in you last comment for the liquid and it seem to be lighter. I would like to know what shades of blue you think we should use. Note: that I have mess around with the liquid's color to find a more suitable shades. Assigning to @jonathanolson for review and suggestions.

**Comment by jonathanolson** [comment]
I haven't done an exhaustive search for differences, but notably:

- emptyBeakerBackside isn't reversed, so the highlight is on the wrong side of the node.
- The beakerBottom should have a flat fill, no gradient (it isn't curved)
- The cap for the liquid should have a flat fill, no gradient (it isn't curved). It also doesn't need to be horizontally swapped.
- The main body/side of the liquid should have a flat fill, since the beakerFront should take care of the reflection highlights here. There should be no liquidFillGradient, just use the color directly (that's the main difference)

Additionally:

- Ideally there should be two tick mark nodes (smallTickNode and bigTickNode?) with copies added where needed, instead of creating a full new Path every time. It should use DAG techniques, e.g. `smallTickLocations.map( function( y ) { return new Node( smallTickNode, { y: y } ) } )`.
- "BeakerFront" should not be fully capitalized ("beakerFront" instead).
- All of the 'line' parts of the curves don't seem needed, see the examples in my code that just use the elliptical arcs.

**Comment by coledu** [comment]
I believe this issue is complete. Assigning to @jonathanolson  for review.
