### ISSUE TITLE
LineWidth default is 1

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/fractions-intro#22]
Specifying `lineWidth: 1` is unnecessary (e.g. in NumberLineIcon).

**Comment by coledu** [comment]
@michaelm396 fixed this issue with his commit 488de23e8cf3f833f4d2ffd1048d4ec42bb65238. Assinging to @jonathanolson for review.

**Comment by jonathanolson** [comment]
I see two usages of this still in BeakerNode, one in NumberLineNode and one in RepresentationPanel?

**Comment by coledu** [comment]
I deleted all the linewidth with the default value. Assigning to @jonathanolson for review.

**Comment by jonathanolson** [comment]
Looks good, thanks!
