### ISSUE TITLE
Text casts numbers to strings

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/fractions-intro#23]
Directly casting to a string, e.g. `new Text( 0 + '', ... )` in NumberLineIcon is not needed.

Furthermore, since those are just constant numbers, I'd recommend replacing with constant strings, since `0 + ''` is just `'0'`.

**Comment by coledu** [comment]
@michaelm396 fixed this issue yesterday with his commit 488de23e8cf3f833f4d2ffd1048d4ec42bb65238. Assigning @jonathanolson to review this issue.

**Comment by jonathanolson** [comment]
Thanks.

Also noticed this is happening in FractionNode (`.text = value + ''`) and MaxSpinner (`maxValueText.text = value + ''`).

**Comment by coledu** [comment]
I took out the casting and searched the intro directory for any other occurrence but did not find any. Assigning back to @jonathanolson for review.

**Comment by jonathanolson** [comment]
Thanks, looks good!
