### ISSUE TITLE
NumberLineIcon options

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/fractions-intro#24]
In RepresentationPanel, the NumberLineIcon is instantiated with:
```
new NumberLineIcon( {
  fill: '#563329',
  lineWidth: 1,
  stroke: 'black'
} )
```
but the passed in options are never used, since NumberLineIcon passes this to Node:
```js
options.children = [ numberLinePath, numberText0, numberText1 ];

Node.call( this, options );
```

I'd recommend removing the options parameter for NumberLineIcon (since usually it would be used for positioning, which RadioButtonGroup takes care of, and inlining the children call:
```js
Node.call( this, {
  children: [ numberLinePath, numberText0, numberText1 ]
} );
```

**Comment by jonathanolson** [comment]
Ideally, things would be inlined further, leaving a simpler-to-read version:
```js
// Draw the lines for the number line symbol for the button icon
var numberLineShape = new Shape().moveTo( 0, 0 )
  .verticalLineToRelative( TICK_HEIGHT )
  .moveTo( LINE_LENGTH, 0 )
  .verticalLineToRelative( TICK_HEIGHT )
  .moveTo( 0, TICK_HEIGHT / 2 )
  .horizontalLineToRelative( LINE_LENGTH );

Node.call( this, {
  children: [
    new Path( numberLineShape, { stroke: 'black' } ),
    new Text( '0', { font: new PhetFont( FONT_SIZE ), centerX: 0, top: TICK_HEIGHT } ),
    new Text( '1', { font: new PhetFont( FONT_SIZE ), centerX: LINE_LENGTH, top: TICK_HEIGHT } )
  ]
} );
```

**Comment by michaelm396** [comment]
I have inlined numberLinePath, numberText0, and numberText1 in the NumberLineIcon.js file. I have also updated the RepresentationPanel.js file to relfect the changes, I am now assigning this issue to @jonathanolson for further review. Thank you.

**Comment by jonathanolson** [comment]
Looks good, thanks!
