### ISSUE TITLE
(read-only) marked on Properties in model

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/fractions-intro#26]
In IntroModel, many of the Properties are marked as `(read-only)`. Generally this indicates that they should not have their value modified by code outside of the file.

Presumably only `this.fractionProperty` is actually read-only, since the others are presumably mutated by other code (e.g. UpDownSpinner with `this.denominatorProperty`), and those documentation labels can be removed?

**Comment by veillette** [comment]
We will follow the convention discussed in the dev meeting from this point on.

**Comment by veillette** [comment]
All the properties are now `@public` except for this.fractionProperty  which has a `@public (read-only)` annotation

**Comment by veillette** [comment]
Assigning back to @jonathanolson  for review.

**Comment by jonathanolson** [comment]
Looks good, thanks!
