### ISSUE TITLE
ICON_SCALE

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/fractions-intro#27]
RepresentationPanel's ICON_SCALE is currently set to `1.00`. Can it be removed, or potentially refactored so that there is a common set of Node options for each icon like `{ scale: 1.2, stroke: 'black' }`?

**Comment by michaelm396** [comment]
I have created a new parameter for "RepresentationPanel.js" named "iconScale" and removed the variable ICON_SCALE from the file. I am assigning the issue to @jonathanolson for further review.

Thank you,
Michael Moorer

**Comment by jonathanolson** [comment]
Looks good, thanks!
