### ISSUE TITLE
Short for centering objects on others

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/fractions-intro#28]
Instead of:
```js
highlighterRectangle.centerX = markerCircle.centerX;
highlighterRectangle.centerY = markerCircle.centerY;
```
it is possible to just say:
```js
highlighterRectangle.center = markerCircle.center;
```

**Comment by coledu** [comment]
On line 184 you can see that I changed the center of the rectangle by setting it to the center of the circle. Assigning to @jonathanolson for review.

**Comment by jonathanolson** [comment]
Looks great, thanks!
