### ISSUE TITLE
Shortcut for setting Line coordinates

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/fractions-intro#29]
Instead of:
```js
mainNumberLine.setX2( segmentLength * max );
```
it's somewhat easier to read when using the ES5 setter:
```js
mainNumberLine.x2 = segmentLength * max;
```

**Comment by coledu** [comment]
I replace mainNumberLine.setX2( segmentLength * max ); with mainNumberLine.x2 = segmentLength * max;. Assigning @jonathanolson for review.

**Comment by jonathanolson** [comment]
Looks good, thanks!
