### ISSUE TITLE
Initial code review for NumberLineNode

### ISSUE THREAD

**Issue by samreid** [phetsims/fractions-intro#3]
I can see that you are making good progress working on NumberLineNode already.  I'll take a look through and see if I have any recommendations.  If I make any commits, I'll link them here so you can take a closer look and follow patterns as you proceed.

**Comment by samreid** [comment]
Some minor changes above, please review them and let me know if you have questions.

Also:
- [x] Consider batching line segments into a single Path.  For instance, using Shape.moveTo.lineTo.moveTo.lineTo, etc.  Then we can have one path for the minor ticks and one for the major ticks.  Not sure how this will work with the highlight region, but I think it will be OK.  May also be better for memory & performance.
- [x] JSDoc needs to be supplied for the top of each file
- [x] I wasn't sure if `numberOfUnits` was the best term, did you consider something like `maxNumberOfUnits` or something that indicates that it is the maximum?  Not sure one way or the other but wanted to make sure you've discussed it.

Everything else is looking great so far, keep up the good work and I'll review again soon.

**Comment by samreid** [comment]
By the way, keep up the good work on the code comments!

**Comment by coledu** [comment]
I have added JSDoc at the top of each file.

**Comment by coledu** [comment]
I use path and shape to make the ticks on the main number line. We use three different paths because we have three different width for minor ticks, odd major ticks, and even major ticks.

**Comment by coledu** [comment]
I believe our task is completed, assigning to @samreid for review.

**Comment by samreid** [comment]
This is coming along nicely!  We can further improve it by factoring out this pattern which appears 3 times:

```js
evenMajorTicksShape.moveTo( i * segmentLength, -IntroConstants.MAJOR_TICK_LENGTH ).verticalLineToRelative( 2 * IntroConstants.MAJOR_TICK_LENGTH );
```

Let's create a new function like this, just before the first for loop:

```js
      /**
       * Append a tick mark to the specified shape.
       * @param {Shape} shape - the shape to append a tick mark to
       * @param {number} x - the x coordinate of the tick mark in view coordinates
       * @param {number} tickLength - the vertical extent of the tick mark in view coordinates
       */
      var appendTick = function( shape, x, tickLength ) {/**/};
```

This will help in factoring out some of the duplicated logic.  Please reassign to me after making this change.

**Comment by coledu** [comment]
Thank you for the suggestion. I have added a function call appendTick that places the tick mark on the number line. Assigning to @samreid

**Comment by samreid** [comment]
Looks great @coledu, nice work!  As you proceed, I'd like you and your team to follow this new process for commits:

If committing a change related to an issue, please copy paste the full path of the issue or the issue number with # sign in the commit message.  For instance, here are some recent commits for this file:

![image](https://cloud.githubusercontent.com/assets/679486/26011807/b8fc1844-370f-11e7-9660-68e30a012cdf.png)

This way, the changes will appear in the issue comment thread, like this:

![image](https://cloud.githubusercontent.com/assets/679486/26011841/d9a8f68e-370f-11e7-9951-37aab414acd7.png)

I'll leave this issue open and assigned to you to make sure you've read this policy change.  After you have read it and your team is aware of this policy, you can close the issue.

**Comment by coledu** [comment]
I have read it and I am aware of it. I will make sure I do this in the future. I have inform my coworker as well. Thanks, I will close this issue.
