### ISSUE TITLE
Inlining of single-use variables

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/fractions-intro#30]
Particularly for Node creation where the only thing done with the variable reference is as a parameter to addChild, I recommend inlining the variable, e.g. changing:

```js
var something = new Text( string, {
  // options
};
parent.addChild( something );
```
to
```js
parent.addChild( new Text( string, {
  // options
} );
```

Noticed this with majorTickLabel in NumberLineNode, but there might be others.

**Comment by davisv7** [comment]
@jonathanolson, I inlined majorTickLabel and looked around for other issues in other files, but I did not see any. Assigning back to you for review.

**Comment by jonathanolson** [comment]
Sounds good, thanks!
