### ISSUE TITLE
Handle screenshot images

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/fractions-intro#31]
It looks like images (0.png - 20.png) were added.

I've applied fixes (removing capitalization of extensions, putting temporary stubs into images/license.json) so that the sim builds properly.

I presume these are temporary, and will be removed as development progresses, so I've created an issue to make sure that's done.

**Comment by coledu** [comment]
I have changed @jonathanolson note in license.js to reflect the actual usage of the images that I have added and explained that these images are temporary and will be removed later. We are using images from the java version for comparison reasons and they will be removed later. Leaving this issue open until we remove the images.

**Comment by coledu** [comment]
I have remove these image. Assigning back to @jonathanolson for review.
