### ISSUE TITLE
Use of Vector2.ZERO

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/fractions-intro#32]
Instead of
```js
new Property( new Vector2( 0, 0 ) );
```
it's recommended to just use
```
new Property( Vector2.ZERO )
```
since the value of the Property itself generally doesn't get mutated. Noticed in Cell.js

**Comment by coledu** [comment]
I have update cell.js to use Vector2.ZERO instead of Vector2(0,0). I did not see we using it again in any other code. Assigning to @jonathanolson for review.

**Comment by jonathanolson** [comment]
Looks good, thanks!

**Comment by jonathanolson** [comment]
Reopening, looks like Piece creates a property based on `new Vector2( 0, 0 )`

**Comment by davisv7** [comment]
I made the change from Vector2( 0,0) to Vector2.ZERO. I looked for but did not find any other instances of this, 

Assigning back to @jonathanolson  for review.

**Comment by jonathanolson** [comment]
Thanks!
