### ISSUE TITLE
NumberLineNode's multiplicationFactorProperty

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/fractions-intro#36]
It gets set only as `new NumberProperty( 1 )` and is never changed. I also don't understand the documentation of what it is supposed to be doing. It seems to control the granularity of number of ticks, but seems like it shouldn't be anything besides 1, but documentation notes it is a ratio between (presumably) how far tick lines go above the line visually vs below?

**Comment by coledu** [comment]
Hello @jonathanolson  ,
Yes the Number do not change from one in the intro tab but when this number is increase it multiple the number of ticks on the number line. We will not use this propetry in the intro tab but will change this for the equality tab. In the image below you can see how the number line is affect when this property is change to four:
![image](https://cloud.githubusercontent.com/assets/26030529/26693396/053608ba-46d2-11e7-95d1-aca972a9d96e.png)
And this image is of the equality tab in the java version:
![image](https://cloud.githubusercontent.com/assets/26030529/26693423/1fbb63f6-46d2-11e7-8e84-513864d46b41.png)
And this is apply to the next couple of issue like the display arrow and having the number line Node rotate vertically.

**Comment by jonathanolson** [comment]
Sounds great. Can the documentation note that it multiplies the quantity of ticks on the bottom?

**Comment by coledu** [comment]
I added the comments to explain multiplicationFactorPropetry, displayArrow, and vertical rotation. Assigning @jonathanolson for review.

**Comment by jonathanolson** [comment]
Looks great, thanks!
