### ISSUE TITLE
CakeNode's maxHeight

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/fractions-intro#37]
A default maxHeight is being set in the options, but this is applied to the grid/cake images AND is applied to the entire CakeNode with the `this.mutate( options );`. Is it meant to restrict the size of the entire CakeNode (in which case it should be documented, and possibly the other usages removed?), or is it meant to just apply to the images?

**Comment by davisv7** [comment]
Pushed commit 69e0014e67e499f39c15cf807ef49639b7bbb5cf that passes max height to this.mutate instead of using it on each image. 

Assigning to @jonathanolson for review.

**Comment by jonathanolson** [comment]
Looks good, thanks!
