### ISSUE TITLE
NumberLineNode's rotation

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/fractions-intro#38]
I only see the horizontal rotation being used. Are there plans to have the number line rotated vertically?

**Comment by jonathanolson** [comment]
Same with `displayArrow`?

**Comment by jonathanolson** [comment]
If rotation is supported, then it should be handled in the markerCircle's drag handler.

**Comment by coledu** [comment]
Hello @jonathanolson ,
See #36. This will explain that the multiplication factor property, rotation, and display arrow will be use later  for the equality lab.

**Comment by jonathanolson** [comment]
Sounds great, thanks!
