### ISSUE TITLE
Center shortcut

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/fractions-intro#39]
Instead of specifying both `centerX: 0` and `centerY: 0` (like the highlighterRectangle in NumberLineNode), it's recommended to just set `center: Vector2.ZERO`.

**Comment by davisv7** [comment]
Done. I checked other modules to see if this appeared elsewhere, and I did not see it anywhere else.

Assigning to @jonathanolson for review.

**Comment by jonathanolson** [comment]
Looks good, thanks!
