### ISSUE TITLE
Code formatting convention

### ISSUE THREAD

**Issue by samreid** [phetsims/fractions-intro#4]
@veillette can you please help make sure your team is set up to use the IntelliJ IDEA code formatting conventions?  I'll commit a reformat for this issue.  If you have any questions or need help setting it up, please let me know.

**Comment by veillette** [comment]
We had setup  IntelliJ IDEA to use the  PhET CodeStyle specified  in the xml file of phetInfo and we have used it pretty diligently when we make commits.
I thought It would be sufficient and would take care  of introducing line breaks for extra long lines.
Is there an additional settings to be specified, or I am missing something?

**Comment by samreid** [comment]
Can you check Settings => Code Style and see if it is set to 120?

![image](https://cloud.githubusercontent.com/assets/679486/26013728/f361b97e-3716-11e7-8412-c6638c533fac.png)

**Comment by veillette** [comment]
It was set to 150 on my machine. Assigning to @michaelm396 , @davisv007  and  @coledu to make sure you have the proper setting in IntelliJ on your computer. Once you have made the change, tick the chekbox below and unassigned yourself for this issue.
 
- [x] Micheal
- [x] Vincent
- [x] Dusty

**Comment by michaelm396** [comment]
All of the team members have updated this setting. In the future, we will try to be more aware of these changes. Closing this issue. Thank you.
