### ISSUE TITLE
Prefer named bounds properties when positioning things

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/fractions-intro#43]
For example, in IntroScreenView's positioning of the ResetAllButton:
```js
right: this.layoutBounds.maxX - 10,
bottom: this.layoutBounds.maxY - 10
```
should ideally be (for readability):
```js
right: this.layoutBounds.right - 10,
bottom: this.layoutBounds.bottom - 10
```
and similar should be done for code based on positioning objects. It's equivalent, as `right` is an alias for `maxX`, etc.

**Comment by davisv7** [comment]
I looked though the program and changed all min/max/x/y to use bounds properties instead. 
Back to @jonathanolson for review.

**Comment by jonathanolson** [comment]
Looks good, thanks!
