### ISSUE TITLE
FractionNode's fill

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/fractions-intro#45]
The option is used as a stroke and a fill. Usually we'd name it 'color' instead?

**Comment by coledu** [comment]
I have refactored fill to color, and searched for any other occurrences. I did not see any more in our project. Assigning back to @jonathanolson for review.

**Comment by jonathanolson** [comment]
Commit seems to have changed to setting the Text's 'color', which doesn't exist. Should be `text.fill = color` and `otherThing.stroke = color`.

**Comment by coledu** [comment]
I have fixed the issue with the color option for FractionsNode. Assigning back to @jonathanolson for review.

**Comment by jonathanolson** [comment]
Looks good, thanks!
