### ISSUE TITLE
FractionNode layout

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/fractions-intro#46]
Let me know if I'm wrong, but it looks like all of the layout is duplicating what a VBox with spacing:2 would do?

No need to horizontally center things, or to set the top/bottom.

**Comment by davisv7** [comment]
Pushed a commit that uses VBox to lay out the fraction. 

Assigning to @jonathanolson for review.

**Comment by jonathanolson** [comment]
Looks good, thanks!
