### ISSUE TITLE
Alternate pattern: supplying children through options

### ISSUE THREAD

**Issue by samreid** [phetsims/fractions-intro#5]
An alternative to using `addChild` calls throughout the code is to coalesce the children and specify them at once.  This can make it easier to view and change the z-ordering, and in some cases leads to simpler code to read and maintain.  It is not always possible to use this pattern, but in several places where it is possible it can be an improvement.  I'll commit an example of one way to do this for NumberLineNode.js.  @veillette can you take a look?

**Comment by samreid** [comment]
Committed above, @veillette can you please review and let me know your thoughts?

**Comment by veillette** [comment]
@samreid , we have followed this pattern in IntroScreenView.js and it works well.

I have informed all the members of the team and we will try to implement this pattern whenever it is possible from this point on.

**Comment by samreid** [comment]
Looks great, thanks! Closing.
