### ISSUE TITLE
Mouse/touch presses on bucket

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/fractions-intro#51]
Usually mouse/touch down on the bucket would act the same as a direct down on the pieces inside the bucket.

Should be fairly trivial with changes for https://github.com/phetsims/fractions-intro/issues/44

**Comment by veillette** [comment]
In the new version of the simulation, the mouse and touch presses on bucket act the same as pressing on the pieces. Assigning to @jonathanolson for review.
