### ISSUE TITLE
Views for pieces/containers/containersets

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/fractions-intro#52]
It was pretty confusing that BeakerNode isn't one beaker, CakeNode isn't one cake, but they are actually essentially containerset nodes (BeakerContainerSetNode).

Can we have separate view nodes for pieces, containers, and container sets if needed? For example, CakePieceNode, CakeContainerNode and CakeContainerSetNode? (ContainerSetNodes may not be needed, as they are probably just hboxes that forward containerset things).

There seems to be a lot of duplicated logic, and causes things like a dummy ContainerSet in BucketNode so that we can display a piece. Shouldn't have to create a full view for a ContainerSet to show one piece.

**Comment by veillette** [comment]
There is a now a very well organized structure with (for instance) CakeView, CalePieceNoce, CakeNode and CakeContainorNode.
