### ISSUE TITLE
Piece.triggerToCell

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/fractions-intro#56]
The following reaches into Cell's state:
```js
  destinationCell.isFilledProperty.value = true;

  // sets the value of incoming Piece to null
  destinationCell.pieceToProperty.value = null;
```
I would slightly prefer if this logic would be moved to a new Cell.fill() method (or equivalent).

**Comment by davisv7** [comment]
Added a method to the cell to perform these actions. Assigning to @jonathanolson  for review.

**Comment by jonathanolson** [comment]
Looks good, thanks!
