### ISSUE TITLE
Piece disposal

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/fractions-intro#57]
It looks like Piece's dispose() unlinks listeners it owns from properties it owns.

Usually disposal would be used to release listeners or references to the Piece that are stored in external objects. When there is no reference to a Piece, a listener of the Piece on a property of the Piece shouldn't prevent any garbage collection or trigger leaks.

**Comment by jonathanolson** [comment]
So, for example, inlining things like animateToCell would be good:
```js
this.cellToProperty.link( function( cell ) {
  if ( cell !== null ) {
    self.animateToAndFrom( self.positionProperty.value, cell.positionProperty.value, {
      onComplete: function() {
        self.triggerToCell();
      }
    } );
  }
} );
```

**Comment by veillette** [comment]
Thanks, I got it reversed. 

I inlined the listener of Piece and removed the piece dispose function.

**Comment by veillette** [comment]
Assigning to @jonathanolson for review.

**Comment by veillette** [comment]
This issue is stale.
