### ISSUE TITLE
Incorrect something in beaker scene

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/fractions-intro#58]
Somehow with toggles I was able to get the sim to this state:
![screen shot 2017-06-09 at 2 04 20 pm](https://user-images.githubusercontent.com/480878/26992604-a1c48eb8-4d1c-11e7-838f-ac6788b02ec2.png)

I would presume it would show a half-full beaker?

If I notice anything about how this happened in the code, I'll update this issue.

**Comment by veillette** [comment]
This issue is stale since it refers to an old implementation of the simulation. Closing.
