### ISSUE TITLE
VerticalBarNode's containerRectangle

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/fractions-intro#59]
It's constructed as:
```js
var containerRectangle = new Rectangle( {
  rectX: -options.containerWidth / 2,
  rectY: -options.containerHeight / 2,
  rectWidth: options.containerWidth,
  rectHeight: options.containerHeight,
  stroke: containerStroke,
  lineWidth: options.outlineLineWidth
} );
```
but its rectX and rectY are essentially never used, as it is positioned by using centerX and centerY. Can rectX and rectY be removed?

**Comment by davisv7** [comment]
You're right, rectX,Y can be removed without issue. Should I do anything with the center X, Y?


Assigning back to @jonathanolson for review.

**Comment by jonathanolson** [comment]
Nothing else needed for the positioning, declaring the width/height and positioning by its center works well.
