### ISSUE TITLE
BucketNode properties

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/fractions-intro#60]
Things like:
```js
    this.pieces = pieces;
    this.denominatorProperty = denominatorProperty;
    this.segmentProperty = segmentProperty;
    this.containerSet = containerSet;
```
should at least have visibility documentation (`@private` or `@public` usually), and things like iconContainerSet (which hopefully can be removed in another issue) would need both visibility and type documentation.

**Comment by michaelm396** [comment]
I have updated the documentation of the public and or private objects of BucketNode. Assigning back to @jonathanolson for further review. Thanks.

**Comment by jonathanolson** [comment]
With the exception of the typo `2private` instead of `@private`, looks good. Can you fix that and close the issue?
