### ISSUE TITLE
add dispose functions to VerticalBarNode, BeakerNode, NumberLineNode, and CakeNode

### ISSUE THREAD

**Issue by veillette** [phetsims/fractions-intro#64]
All the representation nodes do not have a dispose function, leading to memory leaks.

**Comment by jonathanolson** [comment]
Handling this soon would help, as fuzzing causes it to leak many GBs of memory (which is likely to be the culprit for our continuous testing having Chrome crashes lately).

**Comment by coledu** [comment]
We pushed a commit that should add the dispose function for all the existing representations. It is being implemented in IntroScreenView.

**Comment by veillette** [comment]
BucketNode is constantly adding and removing scenery nodes in the bucket  (as well as icon on the bucket). This is a very likely source of memory leak.

**Comment by coledu** [comment]
We will need to go though the proto branch and make sure we dispose of everything that need to be dispose of. Since we switch over to the proto branch is this still an issue with the bucket? What you mention in you last comment.  @veillette .

**Comment by veillette** [comment]
This is no longer a relevant issue. Closing
