### ISSUE TITLE
PROTO: Add documentation to functions of Proto branch. 

### ISSUE THREAD

**Issue by davisv7** [phetsims/fractions-intro#70]
Elements of the proto modules either need annotation or they need their annotation updated.

**Comment by michaelm396** [comment]
Hey @jonathanolson Johnathan, We have been adamantly working to make changes to the prototype fractions intro file. These changes are included in a prioritized checklist to get us started with transitioning the proto branch of Fractions-intro into the master branch (see issue #68 for list). I am going to be assigning you these mapped issues for any further review. Thanks.
