### ISSUE TITLE
PROTO: Properties without listeners should be changed to attributes

### ISSUE THREAD

**Issue by coledu** [phetsims/fractions-intro#71]
Find all the property than are not begin listen to and change them from a property to a simple attribute. This issue was created as a response to a new branch named proto that is linked to #33 .

**Comment by michaelm396** [comment]
Hey @jonathanolson Johnathan, We have been adamantly working to make changes to the prototype fractions intro file. These changes are included in a prioritized checklist to get us started with transitioning the proto branch of Fractions-intro into the master branch (see issue #68 for list). I am going to be assigning you these mapped issues for any further review. Thanks.
