### ISSUE TITLE
PROTO: Remove proto prefix

### ISSUE THREAD

**Issue by davisv7** [phetsims/fractions-intro#72]
Variables with the prefix 'proto' within the proto branch should be refactored without the prefix.

**Comment by veillette** [comment]
The screen view formerly called as intro was deleted. The proto screen view was renamed intro. 
The simulation lints properly and the simulation passes a two minute fuzz mouse test with assertions.

**Comment by veillette** [comment]
Assigning to @jonathanolson  for review

**Comment by jonathanolson** [comment]
Looks good, thanks!
