### ISSUE TITLE
Line separation of cell in containerView

### ISSUE THREAD

**Issue by michaelm396** [phetsims/fractions-intro#76]
Currently the Fractions-proto simulation does not create line separations between the representation Nodes (i.e Circle, Vertical Rectangle, Horizontal Rectangle, Pie) in order to visually show an increase or decrease in denominatorProperty. This should be fairly simple to implement within **(RepresentationNode)ContainerNode**.

**Comment by michaelm396** [comment]
There seems to be an issue with the edgePostion return value that specifically prohibits _i = 8_. This issue, in turn, crashes the entire fractions-intro browser. We tried altering the denominator Number Property in the ProtoModel to values > 8 in order to further troubleshoot. The simulation operated as expected for values of (_i= 9,10,11... etc_) and crashed for i =8. We attempted to fix this issue by multiplying the (CellDividersAngle*i) by a multiplier slightly larger than 1 (i.e. 1.001.), and this quick fix works for the value _i = 8._

```
var edgePosition = Vector2.createPolar( cellDividersLength, 1.001 * i * cellDividersAngle );
        cellDividersShape.moveToPoint( edgePosition ).lineToPoint( Vector2.ZERO );
```
We observed, by reverting Google Chrome back to its original settings, or using another browser (i.e. Firefox) fixes the issues. This allows the sim to operate without a multiplier when _i = 8_.

**Comment by veillette** [comment]
I tested on chrome 59.0.3071 (64 bit),  firefox 54.0 (64 bit) and InternetExplorer 11 without the fudge factor and I did not come across any issues with denominator=8. Hence,  I reverted back the fudge factor.  

Otherwise our work is done here. Assigning to @jonathanolson for review.
