### ISSUE TITLE
BeakerNode should be used to generate an Icon for the Panel Representation

### ISSUE THREAD

**Issue by veillette** [phetsims/fractions-intro#77]
The view of the Beaker Node has hard coded value for the beaker size. You should relax these conditions so that they are passed as options instead. with the hard coded values as default values.

**Comment by coledu** [comment]
Assigning back to @veillette . I made the option to change the size of the beaker. We discuss adding in a perspective or scaling options to avoid use x Radius and Y radius as a options. Also should I have assign you or Jonathon?

**Comment by veillette** [comment]
Good job @coledu. Assigning to @jonathanolson for review.
