### ISSUE TITLE
Add a Representation panel to the simulation

### ISSUE THREAD

**Issue by veillette** [phetsims/fractions-intro#78]
After tackling #77, and adding the number line icon, you should add a RepresentationPanel that replaces the placeholder panel in the Proto Simulation

**Comment by davisv7** [comment]
Forgot to add the tag but I added the representation panel in this commit: a5aa1c6b4219b656c72e053e50fe4e3da7830d17

It's missing two representations because we don't have methods to generate the icons.... yet.

**Comment by veillette** [comment]
The two representations were added, Closing
