### ISSUE TITLE
 Two supertypes call in constructor of IntroScreenView, NumberLineIcon, FractionNode and MaxSpinner

### ISSUE THREAD

**Issue by veillette** [phetsims/fractions-intro#8]
In line 27 of IntroScreenView.js, the command
```
  ScreenView.call( this );
```
is issued and is later reiterated at the end of the constructor in line 58

```
 var options = {
      children: [ resetAllButton, numberLineNode, fractionNode, maxSpinner ]
    };
    ScreenView.call( this, options );
```

Although @samreid suggested to follow  a new pattern to add node to the scene graph, it doesn't imply that we should necessarily have to call to the supertype at the end of the constructor.
You need only one call to the supertype. Since you need to have access to the layountBounds to layout the node (layoutBounds are provided by ScreenView), you need to call the supertype  at the beginning of the constructor. 
However, it is possible to modify the call to the supertype by using the mutate options. 
```
this.mutate( options );
``` 

MaxSpinner.js suffers the same problem

Assigning to @davisv007 since your were responsible for this commit.

**Comment by veillette** [comment]
A similar repetition is found in FractionNode, NumberLineIcon.  This should also be addressed..

**Comment by davisv7** [comment]
I went through IntroScreenView, NumberLineIcon, FractionNode and MaxSpinner and fixed this issue by either deleting the extra call or using the mutate method.

https://github.com/phetsims/fractions-intro/commit/a8f4428a9f90235f3fa86ac8a3c05fe0729e48f9 

(forgot to add the link to commit title, sorry)
