### ISSUE TITLE
Generalize fractionNode to handle MixedNumber

### ISSUE THREAD

**Issue by veillette** [phetsims/fractions-intro#84]
Following recommendation in #66, we should generalize to represent mixed numbers.
See https://en.wikipedia.org/wiki/Fraction_(mathematics)#Mixed_numbers lo learn about MixedNumber.

By default, the fractionNode should display a fraction, but one should be able to toggle the MixedNumber/RegularFraction representation via a public method.

**Comment by coledu** [comment]
Some of the complication that I have thought of was if the denominator is 1 we should never have a fraction and instead a whole number. And why would it make sense to repeat two half of a different object as a whole. I believe this was mentioned in #66 .  I also believe we can move the button to the right side to give us room for the whole number.

**Comment by coledu** [comment]
We have make a commit that implement a mixed number the way we think it might want. We did not want a fraction's numerator to be zero. So we took out the fraction part and make it into a whole number. After discussion we our Berea team we deciding to add the mixed number beside our current improper fraction so we can correctly see the denominator and numerator spinner changing each of their respective number. Below is what the screen might look like giving a few twerks to the size and position on everything. This will be up to the design team to decide.

![image](https://user-images.githubusercontent.com/26030529/27558950-cf950250-5a8c-11e7-8c99-66b3024caa90.png)


And the slider and spinner above the reset button will be remove.

**Comment by veillette** [comment]
Neat.  However, this should bot be enabled by default, so you should remove the equal sign and the MixedNumber, The bucket should be in his habitual place.

Also you should k cheery pick the  options for the FractionNode. Passing any options will fail since you dont want to pass left, bottom, center attributes.

**Comment by coledu** [comment]
5e8ec509fc07252314402f9670e1a250f97878c5. This is the commit that disable the new feature from showing on the screen.

**Comment by amanda-phet** [comment]
I like the direction for this... it makes a lot of sense to show both representations simultaneously, and then we don't have the problem of needing the mixed number to be interactive. 

The design certainly needs some tweaking, but this is a good start. One thing we will need is a radio button pair that toggles the display. So, one option could be "improper fraction" and the other could be "mixed number". Perhaps this could go to the right of the bucket. (Not sure what that spinner is, but I assume it's temporary?)

**Comment by coledu** [comment]
I have and on off switch that toggle the fraction between improper and both. I also remove the slider and thinking about adding a text label above the button to identify it and add dispose function.

**Comment by coledu** [comment]
We do not need a dispose function for this. But a label might still be a good idea.

**Comment by veillette** [comment]
FractionNode has a dispose function.

```
    this.fractionNodeDispose = function() {
      remainderProperty.dispose();
      isRemainderNonZeroProperty.dispose();
      wholeNumberProperty.dispose();
      isWholeNumberNonZeroProperty.dispose();
      fraction.unlinkAttributes();
    };
```
