### ISSUE TITLE
Add Horizontal Bar Representation

### ISSUE THREAD

**Issue by veillette** [phetsims/fractions-intro#85]
The Horizontal bar Representation look like this
![image](https://user-images.githubusercontent.com/7633344/27543478-46a7dbf4-5a58-11e7-908c-f45698213c2d.png)

Currently the CellSceneView display the containerNode inside an HBox,

```
    /**
     * add a container node to the scene graph
     * @param {Container} container
     * @private
     */
    addContainer: function( container ) {
      var containerNode = this.createContainerNode( container, this.onExistingCellDragStart.bind( this ) );

      this.containerNodes.push( containerNode );
      this.containerLayer.addChild( containerNode );
    },

```

It should be generalized to have an VBox inside an HBox. 
 
One should be able to leverage this code to use for the equality lab.

![image](https://user-images.githubusercontent.com/7633344/27543529-6a33dc9e-5a58-11e7-807d-d570b0eba24e.png)

![image](https://user-images.githubusercontent.com/7633344/27543540-723f6c8c-5a58-11e7-9446-6ee77c91806f.png)

**Comment by coledu** [comment]
We use rectangle to make the horizontal bar.

**Comment by michaelm396** [comment]
I have committed features that enables a new HBox to be created inside of the current containerLayer VBox once the maxHorizontalContainers condition is satisfied for the containerNode. This allows containers to lie horizontally parallel to one another. I have also correctly left aligned the containerLayer VBox, that places the new containerNode in alignment with the VBox. These features will be essiential for the life of the horizontal bar node and the equality lab. Assigning this issue back to @veillette for futher review. Thanks for being the best research professor ever! :1st_place_medal:

**Comment by veillette** [comment]
Thanks @michaelm396 , this implementation works well and avoid a lot of duplication. Closing.
