### ISSUE TITLE
PROTO: Issue with dragging a cell

### ISSUE THREAD

**Issue by davisv7** [phetsims/fractions-intro#87]
How to replicate:
When dragging a piece from the bucket or a cell from a container, drag it from its original position on click and rapidly click the piece before it can animate to the container/bucket. Pieces will be generated for as long as you click and they will either go to fill up the container of return to the bucket. You should see something similar to this:

![glitch](https://user-images.githubusercontent.com/8039583/27751244-5e0556d8-5da9-11e7-8859-c649ac5208a3.png)

**Comment by veillette** [comment]
This was addressed by adding an input listener solely to the bucketFront, bucketBack and staticLayers, rather than the entire BucketNode (which includes the moving pieces)

**Comment by veillette** [comment]
Work done. Closing
