### ISSUE TITLE
Location of horizontal bar.

### ISSUE THREAD

**Issue by coledu** [phetsims/fractions-intro#88]
The location of the container for the horizontal bar representation interfere and cross over with the fraction box. This could be move up just a little bit to avoid this. Picture below:
![image](https://user-images.githubusercontent.com/26030529/27751794-0168e586-5dac-11e7-81a3-d0730e7bf970.png)

**Comment by veillette** [comment]
![image](https://user-images.githubusercontent.com/7633344/27914961-c1251586-6232-11e7-83a7-b30bfcb8b57f.png)

**Comment by veillette** [comment]
Changing the alignBound in AlignBox changes the position of the upper left corner. 
Currently it is an fixed value for all representations.
