### ISSUE TITLE
Line comments should have a blank line before them

### ISSUE THREAD

**Issue by samreid** [phetsims/fractions-intro#9]
I noticed code that has this pattern:

```js
    // creates the maxNumberOfUnitsText
    var maxNumberOfUnitsText = new Text( maxNumberOfUnitsProperty.get(), { font: font, fill: options.fill } );
    maxNumberOfUnitsProperty.link( function( value ) {
      maxNumberOfUnitsText.text = value + '';
      // moves maxNumberOfUnitsText to the right of the maxNumberSpinner
      maxNumberOfUnitsText.right = maxNumberSpinner.left - 5;
      // centers maxNumberOfUnitsText vertically with maxNumberSpinner
      maxNumberOfUnitsText.centerY = maxNumberSpinner.centerY;
    } );
```

It is great that you are writing good line comments.  As part of the PhET style, we would like each line comment to be preceded by a blank line.  The entire PhET style guide is available here:
https://docs.google.com/document/d/1Ys1EiwnqQGYuzGOcQSr4uXDes35mF1v1XhMZIl10nk8/edit#heading=h.1oxr3ptyo50w

**Comment by coledu** [comment]
I have acknowledge this issue and inform Vincent and Michael of this issues as well.

**Comment by coledu** [comment]
Everyone is aware. Closing the issue.
