### ISSUE TITLE
PROTO: Create Dropped Shadow behind CircleNode

### ISSUE THREAD

**Issue by michaelm396** [phetsims/fractions-intro#90]
The java Implementation of fractions-intro requires that every piece (vertical node, horizontal node, and circle node) are equipped with a dropped shadow once a click event is active. So far we have a dropped shadow for each piece node except circle node. We noticed that the dropped shadow for the circle piece rotates according to the z-layer. As the piece rotates onto the screenview, the dropped shadow rotates accordingly. @veillette and I worked on this issue but ran into a few problems. Im creating this issues because the dropped shadow for the circle node needs to be further looked into. Assigning this issue to @veillette for further code review. Thank you!

**Comment by veillette** [comment]
This was done in https://github.com/phetsims/fractions-intro/commit/cfb1b32b3bed79128a996adf7233432ec021d4de

**Comment by veillette** [comment]
Work is done. Closing
