### ISSUE TITLE
branch: proto

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fractions-intro#93]
Identified by `print-branches.sh`. @jonathanolson please describe.

**Comment by veillette** [comment]
This branch was developed in the summer of 2017 by @jonathanolson as a prototype to improve performance and model architecture of fractions-intro. Based on this branch, @jonathanolson issued several recommendation (see #33) that were then incorporated in the master branch. 
This should be safe for deletion at this point.

**Comment by jonathanolson** [comment]
Closed the branch (master was up-to-date, and code is in fractions-common)
