### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by arouinfar** [phetsims/fractions-intro#98]
As pointed out in https://github.com/phetsims/QA/issues/267, this sim needs screenshots for 1.0.

**Comment by amanda-phet** [comment]
@phet-steele the main screenshot should match the java version.

**Comment by phet-steele** [comment]
Added the main. Alts are next. My computer says the images are 3072x2016, which is double the desired amount, and this was signed off as okay.

**Comment by amanda-phet** [comment]
>this was signed off as okay. 

It's really easy to resize images so I can do that if we want them at the desired resolution.

**Comment by phet-steele** [comment]
Alright resolutions should now correctly be 1536x1008. Here they are, main first then alts:

![fractions-intro-screenshot](https://user-images.githubusercontent.com/5863899/51766357-94cb1b00-2097-11e9-9517-b4e02f6163ec.png)

![fractions-intro-screenshot-alt1](https://user-images.githubusercontent.com/5863899/51766364-98f73880-2097-11e9-8b98-c6b66379849d.png)

![fractions-intro-screenshot-alt2](https://user-images.githubusercontent.com/5863899/51766365-98f73880-2097-11e9-84bb-522629d05653.png)

![fractions-intro-screenshot-alt3](https://user-images.githubusercontent.com/5863899/51766366-98f73880-2097-11e9-85dd-f089ce488335.png)

**Comment by amanda-phet** [comment]
These all look good to me !
